### ISSUE TITLE
Using only one Channel/Role results in an index Error

### ISSUE THREAD

**Issue by Dastano** [OniSensei/Role-Message-Tracker#1]
Hey man!

Bot working great, was able to test it today on my Private Discord.

However, if you only track one Role/Channel (not sure yet) you get the following Error:

`[ERROR]    System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Role_Message_Tracker.Program.MessageReceivedAsync(SocketMessage message) in C:\Users\tony\source\repos\Role Message Tracker\Role Message Tracker\Program.vb:line 88`

Prefix = "rmt!"
Roles = "Developer"
Channels = "1088148902894653502"

**Comment by OniSensei** [comment]
Thanks for letting me know ill look into this really quick

**Comment by OniSensei** [comment]
Fixed in latest commit / release.
